### PR TITLE
Add more scripts

### PR DESCRIPTION
**Pull request by misterMuyiwa**
This change updates the README with the correct deploy-key steps.
It also introduces patch/minor/deploy scripts pulled from `shyp_api`
It also adds the ability to go through a develop-master-production pipeline

### CODE REVIEW

**Comment by dylanpyle** [comment]
Nice! Couple thoughts:
- Should probably be checking the current working directory state before creating the initial tags (e.g. https://github.com/Shyp/shyp.com/blob/develop/Makefile#L92), not just before the actual deployment
- It would be cool to do the opposite check to https://github.com/Shyp/shyp-toolkit/pull/7/files#diff-2378b82d75acb7d14d7df6a2389e8a02R15 as a preflight for the major/minor/patch scripts - basically, if the current HEAD is already tagged, we shouldn't create another tag for it

**Comment by misterMuyiwa** [comment]
Ah, looks like `shyp.com` is a better source for the minor/major/patch process. I'll use them

**Comment by misterMuyiwa** [comment]
@dylanpyle should be ready for another look https://github.com/Shyp/shyp-toolkit/pull/7/commits/473799ffb9605d90ef4d82437ab51566bb40afef

**Comment by dylanpyle** [comment]
Nice! I think my second comment above would still be a good improvement:

> It would be cool to do the opposite check to https://github.com/Shyp/shyp-toolkit/pull/7/files#diff-2378b82d75acb7d14d7df6a2389e8a02R15 as a preflight for the major/minor/patch scripts - basically, if the current HEAD is already tagged, we shouldn't create another tag for it

We do that in bridge [here](https://github.com/Shyp/bridge/blob/develop/Makefile#L65).

Using the syntax you used for the other check, this could look something like:

```
if git describe --exact-match --tags HEAD ; then
  echo "\033[91mHEAD already has a matching tag, not creating another.\033[0m";
  exit 1;
fi
```

— to be run before each `major`/`minor`/`patch`

**Comment by dylanpyle** [comment]
After that last comment, LGTM!

**Comment by dylanpyle** [comment]
(side note; wow i am really looking forward to getting this one in, clearly we have diverged a lot across projects already)

**Comment by dylanpyle** [comment]
Ahh, OK, I missed those checks in your newest commit. I'm not 100% convinced that continuing silently is better than failing loudly, but this LGTM either way. Thanks for all the time you've put into this one :)

**Comment by misterMuyiwa** [comment]
I've gone ahead to exit loudly. thanks for taking a look

**Pull request merged**
