### PR TITLE
our libraries do not have the same branching strategy as our other app…

### PR DESCRIPTION
**Pull request by misterMuyiwa**
…s, lets reflect that here

### CODE REVIEW

**Comment by kevinburkeshyp** [comment]
Would API or a "main" project (as opposed to a library like shyp-core) ever depend on this project? if so maybe we need `patch-library` and `patch-main` or something, where `main` applies patching based on the branching strategy we use in API

**Comment by misterMuyiwa** [comment]
@kevinburkeshyp good point. i'll update this

**Comment by misterMuyiwa** [comment]
@kevinburkeshyp ready for another pass

**Comment by kevinburkeshyp** [comment]
Might want to add a short descriptive comment like "use this on projects that only have a master branch" or something but LGTM either way.

**Pull request merged**
